{{ if .Values.projects.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kubelab-projects-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - http:
      paths:
      - path: /kubelab/projects/(.+)
        pathType: Prefix
        backend:
          service:
            name: kubelab-projects
            port:
              number: 80
{{ end }}